<a href="https://colab.research.google.com/github/Yassmina-Abdo/linear-algebra/blob/main/01_matrix_multiplication_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [ ]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [ ]:
s= np.int64(5)
v=np.array([ [5],[-2],[4] ])
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B= np.array([[1,2,3],[4,5,6]])
C=np.array([[1,2],[3,4],[5,6]])

print(s)
print(v)
print(A)
print(B)
print(C)

5
[[ 5]
 [-2]
 [ 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [ ]:
#type your code here:
print(type(s))
print(type(v))
print(type(A))


<class 'numpy.int64'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [ ]:
#type your code here:
print(s.shape)
print(v.shape)
print(A.shape)
print(B.shape)
print(C.shape)


()
(3, 1)
(3, 3)
(2, 3)
(3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [ ]:
#type your code here:
print(A[2,1])
A[2,1]=10
print(A)


8
[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [ ]:
#type your code here:
print(A[:,[1]])
print(B[[1],:])


[[ 2]
 [ 5]
 [10]]
[[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [ ]:
#type your code here:
print(np.eye(4))
print(np.zeros(3))
print(np.zeros((3,1)) )
print(np.zeros((3,5)))
print(np.ones((2,3)))
print(np.diag([4,5,6,7]))



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [ ]:
#type your code here:
v1 =np.array([ [1],[2],[7],[4]])
v2 =np.array([[4],[3],[6],[8]])
print(np.add(v1,v2))
print(np.subtract(v1,v2))
print(np.dot(v1,3))
print(np.dot(v1,1/2))




[[ 5]
 [ 5]
 [13]
 [12]]
[[-3]
 [-1]
 [ 1]
 [-4]]
[[ 3]
 [ 6]
 [21]
 [12]]
[[0.5]
 [1. ]
 [3.5]
 [2. ]]


b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [ ]:
#type your code here:
print(np.dot(v1.T,v2))
print(np.matmul(v1.T,v2))
print(v1.T @ v2)


[[84]]
[[84]]
[[84]]


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [ ]:
#type your code here:
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.sqrt(v1.T @ v1))
print(np.sqrt(v2.T @ v2))


8.366600265340756
11.180339887498949
[[8.36660027]]
[[11.18033989]]


d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [ ]:
#type your code here:
u =np.array([ [3],[2],[-1],[4] ])
v =np.array([[1],[-1],[1],[0]])
print(u.T @ v)


[[32]]


# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [ ]:
#type your code here:
A= np.array([[7,3,5],[4,6,2]])
print(np.add(v1,v2))



u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]


 (3A^T)^T = 
 [[21  9 15]
 [12 18  6]]


In [ ]:
u= np.array([[2],[7],[2]])
v= np.array([[8],[2],[4]])

A= np.array([[7,3,5],[4,6,2]])
B= np.array([[0,6,4],[2,3,0]])
print(u)
print(v)
print(A)
print(B)
print(A+B)
print(B+A)
print(np.dot(A,3))
print(np.dot(B,6))
print(np.dot(   np.dot(B,3),2)  )

print(np.dot(A,6) + np.dot(B,15))
print(np.dot(np.dot(A,2) + np.dot(B,5),3))
print(np.dot(A.T,3).T)




[[2]
 [7]
 [2]]
[[8]
 [2]
 [4]]
[[7 3 5]
 [4 6 2]]
[[0 6 4]
 [2 3 0]]
[[7 9 9]
 [6 9 2]]
[[7 9 9]
 [6 9 2]]
[[21  9 15]
 [12 18  6]]
[[ 0 36 24]
 [12 18  0]]
[[ 0 36 24]
 [12 18  0]]
[[ 42 108  90]
 [ 54  81  12]]
[[ 42 108  90]
 [ 54  81  12]]
[[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [ ]:
print(A@u + A@v)

print(A @(u +v))
print((A +B)@ u)
print(A @(3 *u))
print(3*A @ u)

[[127]
 [106]]
[[127]
 [106]]
[[95]
 [79]]
[[135]
 [162]]
[[135]
 [162]]


In [ ]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries 

In [ ]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[9. 8. 0. 6.]
 [5. 1. 3. 5.]
 [6. 8. 0. 6.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix). 

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [ ]:
#type your code here:
R = np.copy(A)
R[0, :] = R[0, :] / R[0, 0]
R[1, :] = R[1, :] - R[1, 0] * R[0, :]
R[2, :] = R[2, :] - R[2, 0] * R[0, :]
print(R)


[[ 1.          0.88888889  0.          0.66666667]
 [ 0.         -3.44444444  3.          1.66666667]
 [ 0.          2.66666667  0.          2.        ]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [ ]:
#type your code here:
R[1, :] = R[1, :] / R[1, 1]
R[0, :] = R[0, :] - R[0, 1] * R[1, :]
R[2, :] = R[2, :] - R[2, 1] * R[1, :]
print(R)


[[ 1.          0.          0.77419355  1.09677419]
 [-0.          1.         -0.87096774 -0.48387097]
 [ 0.          0.          2.32258065  3.29032258]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [ ]:
#type your code here:
R[2, :] = R[2, :] / R[2, 2]
R[0, :] = R[0, :] - R[0, 2] * R[2, :]
R[1, :] = R[1, :] - R[1, 2] * R[2, :]
print(R)



[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  7.50000000e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.41666667e+00]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [ ]:
#type your code here:
print('Rank = ',np.linalg.matrix_rank(R))
M = sym.Matrix(A)
M_rref = M.rref()
print('solution:\n', R)
R = np.array((M_rref[0])).astype(np.float64)
print('\nrref solution:\n', R)

# Use sympy.rref() method 


Rank =  3
solution:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  7.50000000e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.41666667e+00]]

rref solution:
 [[1.         0.         0.         0.        ]
 [0.         1.         0.         0.75      ]
 [0.         0.         1.         1.41666667]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$. 
 
2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [ ]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        for j in range(p):
            C[i,j] =np.dot(  A[i,:],B[:,j] )

    ########################################################        
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for j in range(p):
        C[:,j] = np.dot(A,B[:,j])

    ########################################################         
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        C[i,:]= np.dot(A[i,:],B)

    ########################################################         
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(n):
            C += np.dot(A[:,[i]],B[[i],:])

    ########################################################         
    return C

In [ ]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [ ]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5941. 5771. 6303. ... 5937. 6429. 6205.]
 [5868. 5978. 6526. ... 6085. 6343. 6215.]
 [6018. 5865. 6222. ... 6319. 6152. 6146.]
 ...
 [5749. 5514. 6097. ... 5789. 5860. 6068.]
 [6334. 5927. 6296. ... 6337. 6376. 6360.]
 [5852. 5423. 6163. ... 6013. 6419. 6287.]]
Wall time: 5.99 ms


In [ ]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5941. 5771. 6303. ... 5937. 6429. 6205.]
 [5868. 5978. 6526. ... 6085. 6343. 6215.]
 [6018. 5865. 6222. ... 6319. 6152. 6146.]
 ...
 [5749. 5514. 6097. ... 5789. 5860. 6068.]
 [6334. 5927. 6296. ... 6337. 6376. 6360.]
 [5852. 5423. 6163. ... 6013. 6419. 6287.]]
Wall time: 369 ms


In [ ]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5941. 5771. 6303. ... 5937. 6429. 6205.]
 [5868. 5978. 6526. ... 6085. 6343. 6215.]
 [6018. 5865. 6222. ... 6319. 6152. 6146.]
 ...
 [5749. 5514. 6097. ... 5789. 5860. 6068.]
 [6334. 5927. 6296. ... 6337. 6376. 6360.]
 [5852. 5423. 6163. ... 6013. 6419. 6287.]]
Wall time: 18 ms


In [ ]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5941. 5771. 6303. ... 5937. 6429. 6205.]
 [5868. 5978. 6526. ... 6085. 6343. 6215.]
 [6018. 5865. 6222. ... 6319. 6152. 6146.]
 ...
 [5749. 5514. 6097. ... 5789. 5860. 6068.]
 [6334. 5927. 6296. ... 6337. 6376. 6360.]
 [5852. 5423. 6163. ... 6013. 6419. 6287.]]
Wall time: 87.1 ms


In [ ]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5941. 5771. 6303. ... 5937. 6429. 6205.]
 [5868. 5978. 6526. ... 6085. 6343. 6215.]
 [6018. 5865. 6222. ... 6319. 6152. 6146.]
 ...
 [5749. 5514. 6097. ... 5789. 5860. 6068.]
 [6334. 5927. 6296. ... 6337. 6376. 6360.]
 [5852. 5423. 6163. ... 6013. 6419. 6287.]]
Wall time: 63.9 ms
